### ISSUE TITLE
create flow to download cubes from gbif

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#18]
- [x] create cron triggered github action to download cubes from gbif
- [x] place cube files in input - folder 
- [x] change [05_occurrence_indicators_preprocessing.Rmd](https://github.com/inbo/aspbo/blob/main/src/05_occurrence_indicators_preprocessing.Rmd) to start from downloaded files
- [x] change `create full_timeseries.csv` - workflow to trigger when download workflow was succesful, see trigger code:
```
on:
 workflow_run:
 workflows: [download_cubes]
 types:
 - completed
```

**Comment by SanderDevisscher** [comment]
@damianooldoni what is the status on downloading the species cubes directly from gbif ?

**Comment by damianooldoni** [comment]
Hi @SanderDevisscher: unfortunately this is not planned for 2023 yet, my mistake.
But they can create cubes on demand if you need them.

I will aks for an occurrence cube. Are these below your requirements?

CONSTRAINTS:
1. taxonomic: everything
2. time: everything
3. space: Belgium

GRANULARITY:
1. taxonomic: taxa as mentioned in the GRIIS checklist (some are species, some subspecies, some are genus...)
2. time: year
3. space: 1x1km EEA grid

 If they will not be able to provide it (very unlikely), then I will produce it as I did the last years.

**Comment by damianooldoni** [comment]
FYI, you can follow my request to GBIF here: https://github.com/gbif/occurrence-cube/issues/3

**Comment by SanderDevisscher** [comment]
> Het heeft iets meer geduurd dan verwacht, maar het was de moeite waard denk ik 🙂
> Github page: https://damianooldoni.github.io/b3cubes-sql-examples/
> GitHub repo: https://github.com/damianooldoni/b3cubes-sql-examples
> 
> Zoals vermeld in homepage zelf, idee is om deze documentatie toevoegen aan officiële https://docs.b-cubed.eu/. Ik heb hierover issue geopend ([#44](https://github.com/b-cubed-eu/documentation/issues/44)).
> 
> Enjoy cubing!

_posted by @damianooldoni on 2024-09-11 in google chat_

**Comment by damianooldoni** [comment]
Update: there is a rgbif function to trigger SQL API: [`occ_download_sql()`](https://docs.ropensci.org/rgbif/reference/occ_download_sql.html)  🥳
I would not change the written tutorials. I would add a new; short one, I suppose.

**Comment by SanderDevisscher** [comment]
Thanks for the update 😄

**Comment by SanderDevisscher** [comment]
```
To pass parameters from a GitHub Actions runner to an R Markdown (.Rmd) file, you can utilize the params feature in R Markdown along with the rmarkdown::render() function in your GitHub Actions workflow. Here’s how to set it up:
Step-by-Step Setup
1. Modify Your R Markdown Document
First, ensure your R Markdown file is set up to accept parameters. You can define parameters in the YAML header of your .Rmd file like this:
text
---
title: "Parameterized Report"
output: html_document
params:
  my_param: NULL
---

```{r}
# Use the parameter in your analysis
cat("The parameter value is:", params$my_param, "\n")

text

### 2. **Create or Edit Your GitHub Actions Workflow**

Next, create or edit a workflow YAML file in your repository (e.g., `.github/workflows/render-rmd.yml`). Below is an example of how to set up the workflow to pass parameters to the R Markdown document:

```yaml
name: Render R Markdown

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages("rmarkdown")'

      - name: Render R Markdown with parameters
        run: |
          Rscript -e 'rmarkdown::render("path/to/your_file.Rmd", params = list(my_param = "value1"))'

3. Explanation of Workflow Steps
Checkout repository: This step checks out your repository so that the workflow can access your .Rmd file.
Set up R: This step installs R on the runner.
Install dependencies: Here, you install any necessary packages, including rmarkdown.
Render R Markdown with parameters: This step runs an R command to render the .Rmd file and passes the parameter my_param with a specific value (e.g., "value1").
4. Using Different Parameters
If you want to run the same script with different parameters in parallel, you can use a job matrix. Here’s how to modify the workflow:
text
name: Render R Markdown with Parameters

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        param_value: ["value1", "value2", "value3"]  # Different parameter values

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages("rmarkdown")'

      - name: Render R Markdown with parameter
        run: |
          Rscript -e 'rmarkdown::render("path/to/your_file.Rmd", params = list(my_param = "${{ matrix.param_value }}"))'

Summary
By following these steps, you can effectively pass parameters from a GitHub Actions runner to an R Markdown document. This setup allows for dynamic report generation based on different input values, enhancing automation and flexibility in your workflows.

**Comment by SanderDevisscher** [comment]
```
In Workflow A (Upload Artifact):
Create a job that generates the .csv file and uploads it as an artifact.
text
name: Workflow A
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate CSV
        run: |
          echo "Column1,Column2" > output.csv
          echo "Data1,Data2" >> output.csv

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-csv-file
          path: output.csv

In Workflow B (Download Artifact):
Set up a workflow that triggers on the completion of Workflow A and downloads the artifact.
text
name: Workflow B
on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download CSV artifact
        uses: actions/download-artifact@v2
        with:
          name: my-csv-file

      - name: Use CSV file
        run: |
          cat output.csv  # Replace with your processing logic.
```
