### ISSUE TITLE
Create dataflow to publish alienspecies cubes on ZENODO

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#270]
The cubes will be downloaded monthly by the [get_occ_cube](https://github.com/inbo/aspbo/blob/uat/.github/workflows/get_occ_cube.yaml) github action (after #18). 
Since this information would be interesting for other researchers (in and outside of INBO) we should publish the cube to ZENODO. 

@damianooldoni we should plan a meet to determine the best way to achieve this.

**Comment by SanderDevisscher** [comment]
A new workflow should be created to update eu_alientaxacube on Zenodo. It should be triggered when the [get_occ_cube](https://github.com/inbo/aspbo/blob/uat/.github/workflows/get_occ_cube.yaml) - workflow is completed successfully. This new workflow will run in parallel with the [cube preprocessing](https://github.com/inbo/aspbo/blob/uat/.github/workflows/cube_preprocessing.yaml) - workflow. 

Todo:
- [x] add logic to log download doi's to get_occ_cube flow
- [ ] @damianooldoni adds a access token to this repo's secrets
- [ ] use [deposits](https://docs.ropensci.org/deposits/) to update eu_alientaxacube on zenodo

Taxon metadata is not yet included in b-cubed flow see https://github.com/gbif/occurrence-cube/issues/9 for updates

**Comment by SanderDevisscher** [comment]
@damianooldoni can you provide a link to the zenodo dataset to be updated ?

**Comment by damianooldoni** [comment]
https://doi.org/10.5281/zenodo.3632749

**Comment by SanderDevisscher** [comment]
@damianooldoni do we need other info besides the DOI of the component downloads (1 for each rank cube + class cube) ?

**Comment by SanderDevisscher** [comment]
The flow is running, see [![download occurrence cube](https://github.com/inbo/aspbo/actions/workflows/get_occ_cube.yaml/badge.svg?branch=270-add-doi-compilation-to-download-cubes-flow)](https://github.com/inbo/aspbo/actions/workflows/get_occ_cube.yaml)

**Comment by damianooldoni** [comment]
I think it's enough.

**Comment by SanderDevisscher** [comment]
this flow failed on an other job, but here is how the final metadata file would look like: https://github.com/inbo/aspbo/actions/runs/13016533798/artifacts/2499619831

[be_cube_metadata.csv](https://github.com/user-attachments/files/18585414/be_cube_metadata.csv)

I suggest the next step would be to create a seperate github action with the following parts in the .yaml file:

To trigger upon succesful completion of the previous flow
```
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["download occurrence cube"]
    types:
      - completed

jobs:
  fetch-data:
    runs-on: ${{ matrix.config.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
```

To retrieve the metadata and both cubes:
```
     - name: Get latest successful run ID 
        id: get-latest-run
        run: |
          run_id=$(gh run list -w get_occ_cube.yaml --status success --json databaseId --jq '.[0].databaseId')
          echo "run_id=$run_id" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download be_alientaxa_cube artifact
        uses: actions/download-artifact@v4
        with:
          name: be_alientaxa_cube.csv
          path: ./cube_data/
          run-id: ${{ steps.get-latest-run.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-multiple: true

     - name: Download be_classes_cube artifact
        uses: actions/download-artifact@v4
        with:
          name: be_classes_cube.csv
          path: ./cube_data/
          run-id: ${{ steps.get-latest-run.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-multiple: true

     - name: Download metadata artifact
        uses: actions/download-artifact@v4
        with:
          name: be_cube_metadata.csv
          path: ./cube_data/
          run-id: ${{ steps.get-latest-run.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-multiple: true
```

This github action would do the neccesary steps to upload the cubes to zenodo.
